spring.application.name=SpringRestdemo

rsa.public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwZEeJRJUHWbemgXiGv14ca2XS9nVSpNWy2dYvyP4xd2NNLnxxFa9VL9Q4QF1DkOY4Zs72sSmCAemnbIQ362BFyPFCoIyWHcDFHN8BTHThG05BHa7IUzit6xmwYaJl0Z91ZkeiaWGBwSimaEfUNKcjo951lADrE4WZ67JqeeV1HngMoth3RyBRdYVft5xAGM5saBmAFVKaKLtT1Dqm0gvh60l6IF3okwMUiMKwKXqDe+PTQn3jZhJwotn3bqoOoA5F++LV0xYLGTl2AgyxqhzmAEWP1z8weJYcgHwAXnOLieAf9esq+vA0XK7U1WYbK4+34No0Fz3sFonrRHXu3pmzwIDAQAB

rsa.private-key=MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDBkR4lElQdZt6aBeIa/XhxrZdL2dVKk1bLZ1i/I/jF3Y00ufHEVr1Uv1DhAXUOQ5jhmzvaxKYIB6adshDfrYEXI8UKgjJYdwMUc3wFMdOEbTkEdrshTOK3rGbBhomXRn3VmR6JpYYHBKKZoR9Q0pyOj3nWUAOsThZnrsmp55XUeeAyi2HdHIFF1hV+3nEAYzmxoGYAVUpoou1PUOqbSC+HrSXogXeiTAxSIwrApeoN749NCfeNmEnCi2fduqg6gDkX74tXTFgsZOXYCDLGqHOYARY/XPzB4lhyAfABec4uJ4B/16yr68DRcrtTVZhsrj7fg2jQXPewWietEde7embPAgMBAAECggEAFXak9BFjOFtmxYdvefSvPVO1WhjOeNV7o1RTV+aCOFaHyNfxggboOZR5QGnr8+f09NdEvM5fZraKeCP9kP/pN4qk17R2Jq8TrVnc36qVvLJrxx3vRBMFdL5uKnljml2bqGqxIywyf2a5LPXbxheEep5YMTZwIdQK0fZksC1YxNWJcRmPyceyocpDfJbiKSupZIyCuKMoCeOvs5ljUTzBfKYflPG2nL0S4SdwQX5WNexE+cfoEtPCMTNgQpkUn4S3vcv+kIOHZLgz1Vx/DKObv8NkGMJGe+jDpYir28U/8QTp1fQr+lq3eMEvhA+dO1BaAACf1MKtlqlF65uN+juKqQKBgQDjGZBXlU7aAPQvlSWHFbAeNpIcvNVfzTbet3v5nVes49aivTDRdv+4

# Server port
Server.port=8080

# Database config
spring.datasource.url=jdbc:h2:file:./db/db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#setup local h2 database console
spring.h2.console.enabled=true
spring.h2.console.path=/db-console
spring.h2.console.settings.web-allow-others=false

# local h2 tables setup on startup; use the value "none" In production!
spring.jpa.hibernate.ddl-auto=create-drop

# Logging setting
logging.level.org.studyeasy.SpringStarting= DEBUG
logging.pattern.console=%d [%level] %c{1.} [%t] %m%n
logging.file.name= = appLog.log
logging.pattern.file= %d [%level] %c{1.} [%t] %m%n

logging.level.org.springframework.security=DEBUG

#File settings

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
#spring.mvc.static-path-pattern=/resources/static/**f